---
title: "Angelice_Project3 Education Level: `r params$edlvl` "
author: "Angelice Floyd"
params:
  edlvl: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r rndr, eval = FALSE, echo = FALSE}

lapply(c(1,3,4,5,6),function(x) {rmarkdown::render("Project3_draft.Rmd",
              params = list(Education1 = 1)
              output_format = "github_document", 
              output_options = list(
                name_value_pairs = "value", 
                toc = TRUE,
                toc_depth = 4, 
                number_of_sections = TRUE, 
                df_print = "paged", 
                or_something = TRUE,
                html_preview = FALSE,
                params = list(edlvl = x),
                output_file = paste0("Project3",x,".HTML")
                
                )
              )
}
)
```


Introduction : Insert Michael's intro here 

```{r libraries}

library(tidyverse)
library(caret)
library(GGally)
library(shiny)
```


# Reading in the Data 

Below reads in the binary heart disease data, converts the appropriate variables into factor level variables, and splits the data into training and test set data. 

```{r readin}
initial_dta <- read_csv('diabetes_binary_health_indicators_BRFSS2015.csv') %>% mutate( Education1 = ifelse(Education %in% c(1,2),1,Education))

cols <- c("Diabetes_binary","PhysActivity","AnyHealthcare","Education1","HighBP",
          "Smoker","Fruits","NoDocbcCost","Income","DiffWalk","HighChol","Stroke",
          "Veggies","GenHlth","Sex","CholCheck","HeartDiseaseorAttack","HvyAlcoholConsump",
          "MentHlth")
  
initial_dta[cols] <- lapply(initial_dta[cols],factor)

#set see for reproducability 

set.seed(90)

#create a training index that uses 70% of the data for training data

trainindex <- createDataPartition(initial_dta$Diabetes_binary,p = 0.70, list= FALSE)

#Now, split the data into 70% training and 30% testing

initial_dta_train <- initial_dta[trainindex, ]
initial_dta_test <- initial_dta[-trainindex, ]

#To help make our predictions valid, we are now going to standardize the numeric variables

preprocval <- preProcess(initial_dta_train,method = c("center","scale"))

trainTransformed <- as_tibble(predict(preprocval,initial_dta_train))


testTransformed <- as_tibble(predict(preprocval,initial_dta_tes))



```